# Input-output models


<a id='index-0'></a>

Here we use python in the jupyter notebook. 

In the notebook, you evaluate (or "run") the python code by pressing the `SHIFT` and `ENTER` keys simultaneously.

In this notebook we use the numpy library that we import:

In [1]:
import numpy as np

## Theoretical part 

Suppose we have the following vector $x$:

$$x=\begin{bmatrix}
    1\\
    2\\
    3 
\end{bmatrix} $$

We write this in python as demonstrated below.

In [2]:
x = np.matrix([[1],[2],[3]])
x

matrix([[1],
        [2],
        [3]])

Suppose we have the following vector $y$:
$$y=\begin{bmatrix}
    4\\
    5\\
    6 
\end{bmatrix}$$

Again, we write this in python as demonstrated below.

In [3]:
y = np.matrix([[4],[5],[6]])
y

matrix([[4],
        [5],
        [6]])

Using python we can easily calculate the matrix-vector product $y^Tx$ as follows:

In [4]:
yTx = np.transpose(y)*x
yTx

matrix([[32]])

**Exercise**

Now calculate $x^Ty$, $xy^T$ and $yx^T$ yourself. What do you notice?

In [5]:
xTy = np.transpose(x)*y
xyT = x*np.transpose(y)
yxT = y*np.transpose(x)
print(yTx)
print(xTy)
print(xyT)
print(yxT)

[[32]]
[[32]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


I notice that if we first transpose and then multiply we get a 1x1 matrice. This makes sense, if we first transpose and then we get a 3x3 matrix, which makes sense too.

Suppose we have the following matrix $A$:

$$A=\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6\\
    7 & 8 & 9 
\end{bmatrix}$$

We write this in python as demonstrated below.

In [6]:
A = np.matrix([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Using python we can easily calculate the product $A^TA$ as follows:

In [7]:
ATA = np.transpose(A)*A
ATA 

matrix([[ 66,  78,  90],
        [ 78,  93, 108],
        [ 90, 108, 126]])

**Exercise**

Now calculate $AA^T$ yourself. What do you notice?

In [8]:
AAT = A*np.transpose(A)
print(ATA)
print(AAT)

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


I notice that the answer is different, again this makes sense. When multiplying matrices it matters in what order you do it!

Now suppose we have the following matrix $B$:

$$B=\begin{bmatrix}
    1 & 2 & 3 & 4\\
    5 & 6 & 7 & 8\\
    9 & 10 & 11 & 12 
\end{bmatrix}$$

**Exercise**

Calculate $B^TB$ and $BB^T$. What do you notice?

In [9]:
B = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
BTB = np.transpose(B)*B
BBT = B*np.transpose(B)
print(BTB)
print(BBT)

[[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


Let $e_1$ be the first unit vector:
$$e_1=\begin{bmatrix}
    1\\
    0\\
    0\\
    0
\end{bmatrix}$$

Similarly we have unit vectors $e_2$, $e_3$ and $e_4$. 

**Exercise**

Calculate $Be_1$, $Be_2$, $Be_3$ and $Be_4$. What do you notice?

In [10]:
B = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
e1 = np.matrix([[1],[0],[0],[0]])
e2 = np.matrix([[0],[1],[0],[0]])
e3 = np.matrix([[0],[0],[1],[0]])
e4 = np.matrix([[0],[0],[0],[1]])
Be1 = B*e1
Be2 = B*e2
Be3 = B*e3
Be4 = B*e4
print(Be1)
print(Be2)
print(Be3)
print(Be4)

[[1]
 [5]
 [9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]
[[ 4]
 [ 8]
 [12]]


Multiplying the vector by the unit vector gives the corresponding column. So Be1 returns column one from B, Be2 returns column two from B, etc.

## Application: input-output models (part 1)

A chemical plant receives oil from three different regions: the Middle East, South America, and the North Sea. The quality of the oil is different for each region. These oils will be used to produce gasoline, diesel fuel, and lubricating oil. The oil from the Middle east will be only used for the production of gasoline. Of the oil of South America, 20 % will be used
for the production of gasoline, and 80 % for the production of diesel fuel. Finally, 25 % of the North Sea oil will be used to produce gasoline, 25 % to produce diesel fuel, and 50 % for the production of lubricating oil. 

Suppose today a shipment arrives of 5000 barrels of oil from the Middle East, 9000 barrels of oil from South America, and 1000 barrels from the North Sea. The plant wants to know how much gasoline, diesel fuel, and lubricating oil it can produce from this shipment. 

Obviously, the 5000 barrels of oil from the Middle East will completely be used for the production of gasoline, i.e. 1 · 5000 = 5000 barrels of gasoline. Of the 9000 barrels of South America oil, 20 % will be used for the produc-
tion of gasoline. Hence, this leads to 0.2 · 9000 = 1800 barrels of gasoline. Finally, of the 1000 barrels of North sea oil 25 % will be used for the production of gasoline. Hence, we obtain 0.25 · 1000 = 250 barrels of gasoline. Hence, the total number of barrels of gasoline that will be produced is

$$1 · 5000 + 0.2 · 9000 + 0.25 · 1000 = 5000 + 1800 + 250 = 7050.$$

Similarly, we obtain the total number of barrels of diesel fuel,

$$0 · 5000 + 0.8 · 9000 + 0.25 · 1000 = 0 + 7200 + 250 = 7450,$$

and the total number of barrels of lubricating oil,

$$0 · 5000 + 0 · 9000 + 0.5 · 1000 = 0 + 0 + 500 = 500.$$

Hence, the oil-delivery will result in 7050 barrels of gasoline, 7450 barrels of diesel fuel, and 500 barrels of lubricating oil.

This production process can be summarized using the matrix-vector product. The production process can be represented by the following matrix:

$$A=\begin{bmatrix}
    1 & 0.2 & 0.25\\
    0 & 0.8 & 0.25\\
    0 & 0 & 0.50 
\end{bmatrix}$$

where the first column represents the division in the three end products of the Middle East oil, the second column represents the division in the three end products of the South America oil, and the third column represents the
division in the three end products of the North Sea oil. 

In [11]:
A = np.matrix([[1, 0.2, 0.25],[0, 0.8, 0.25], [0,0,0.5]])
A

matrix([[1.  , 0.2 , 0.25],
        [0.  , 0.8 , 0.25],
        [0.  , 0.  , 0.5 ]])

The shipment of the oil can be summarized by the following vector:

$$q=\begin{bmatrix}
    5000\\
    9000\\
    1000 
\end{bmatrix}$$

In [12]:
q = np.matrix([[5000],[9000], [1000]])
q

matrix([[5000],
        [9000],
        [1000]])

Using the matrix-vector product, it can easily be calculated how much gasoline, diesel fuel, and lubricating oil can be produced from this oil-delivery.

\begin{align}
Aq&=\begin{bmatrix}
    1 & 0.2 & 0.25\\
    0 & 0.8 & 0.25\\
    0 & 0 & 0.50 
\end{bmatrix} \begin{bmatrix}
    5000\\
    9000\\
    1000 
\end{bmatrix}\\
& = \begin{bmatrix}
    1 \times 5000 + 0.2 \times 9000 + 0.25 \times 1000\\
    0 \times 5000 + 0.8 \times 9000 + 0.25 \times 1000\\
    0 \times 5000 + \ \ 0 \times 9000 + 0.50 \times 1000 
\end{bmatrix}\\
& = \begin{bmatrix}
7050\\
7450\\
500
\end{bmatrix}
\end{align}

In [13]:
Aq=A*q
Aq

matrix([[7050.],
        [7450.],
        [ 500.]])

Hence, using the matrix-vector product we come to the same conclusion: the oil-delivery will result in 7050 barrels of gasoline, 7450 barrels of diesel fuel, and 500 barrels of lubricating oil.

**Exercise 1.11** (matrix-vector product)

The next day a shipment of 10000 barrels of oil from the Middle East, 1000 barrels of
South America, and 200 barrels of the North Sea arrives. Determine the output of gasoline,
diesel fuel, and lubricating oil of this oil-delivery.

In [14]:
n = np.matrix([[10000],[1000], [200]])
An = A*n
print(An)

[[10250.]
 [  850.]
 [  100.]]


## Application: input-output models (part 2)

Now a chemical plant receives oil from five different regions: the Middle East, South America, the North Sea, Africa and Asia. Again, the quality of the oil is different for each region. These oils will be used to produce gasoline, diesel fuel, lubricating oil, fuel 95 and fuel 98. The oil from the Middle east will be only used for the production of gasoline. Of the oil of South America, 20 % will be used for the production of gasoline, and 80 % for the production of diesel fuel. 25 % of the North Sea oil will be used to produce gasoline, 25 % to produce diesel fuel, and 50 % for the production of lubricating oil. Of the oil of Africa, 10 % will be used for the production of gasoline, 10 % for the production of lubricating oil, 30 % for the production of fuel 95 and 50 % for the production of fuel 98. Finally, 30 % of the Asia oil will be used to produce gasoline, 5 % to produce diesel fuel, 50 % for the production of fuel 95, and 15% for the production of fuel 98.

Suppose today a shipment arrives of 5000 barrels of oil from the Middle East, 9000 barrels of oil from South America, 1000 barrels from the North Sea, 4000 barrels of oil from Africa, and 4000 barrels of oil from Asia. The plant wants to know how much gasoline, diesel fuel, lubricating oil, fuel 95, and fuel 98 it can produce from this shipment. 

**Exercise** (matrix-vector product)
With the new information, $A$ will be a 5x5 matrix and $q$ will be a 5x1 vector. Determine the output of gasoline, diesel fuel, lubricating oil, fuel 95, and fuel 98 of this oil-delivery.

In [15]:
#first row will be gasoline, second row will be diesel and 3rd is lubricating oil, 4rth = fuel 95 and 5th = fuel 98, 
#columns are in order listed in question.
B = np.matrix([[1, 0.2, 0.25, 0.1, 0.3],[0, 0.8, 0.25, 0, 0.05], [0,0,0.5,0.1,0], [0,0,0,0.3,0.5], [0,0,0,0.5,0.15]])
B

matrix([[1.  , 0.2 , 0.25, 0.1 , 0.3 ],
        [0.  , 0.8 , 0.25, 0.  , 0.05],
        [0.  , 0.  , 0.5 , 0.1 , 0.  ],
        [0.  , 0.  , 0.  , 0.3 , 0.5 ],
        [0.  , 0.  , 0.  , 0.5 , 0.15]])

In [16]:
#defining vector q
q = np.matrix([[5000],[9000], [1000], [4000], [4000]])
q

matrix([[5000],
        [9000],
        [1000],
        [4000],
        [4000]])

In [17]:
#now we simply multiply as follows; 
Bq = B*q
print(Bq)

[[8650.]
 [7650.]
 [ 900.]
 [3200.]
 [2600.]]
